language: java

sudo: true

jdk:
  - openjdk8

cache:
  directories:
  - $HOME/.m2

env:
  - KUBECTL_VERSION=v1.13.3
  - KUBECTL_VERSION=v1.12.5
  - KUBECTL_VERSION=v1.11.7
  - KUBECTL_VERSION=v1.10.13
  - KUBECTL_VERSION=v1.9.11
  - KUBECTL_VERSION=v1.8.15

install:
- curl -LO https://storage.googleapis.com/kubernetes-release/release/$KUBECTL_VERSION/bin/linux/amd64/kubectl
- chmod +x ./kubectl
- sudo mv ./kubectl /usr/local/bin/kubectl

after_success:
- mvn clean test findbugs:check jacoco:report coveralls:report
